FROM node:lts AS image
WORKDIR /app
COPY ./package.json .

FROM image AS build
RUN npm pkg set scripts.prepare=" "
RUN npm install --legacy-peer-deps
COPY . .
RUN npm run webpack

EXPOSE 3003

CMD ["npm", "run", "start"]
