FROM node:22.0.0-alpine AS image
WORKDIR /app
COPY ./package.json .

FROM image AS build
RUN npm pkg set scripts.prepare=" "
RUN npm install --legacy-peer-deps
COPY . .
RUN npm run webpack

EXPOSE 3003
ENV REACT_APP_ENABLE_HIDDEN_FEATURES TRUE

CMD ["npm", "run", "start"]
